"""Initial schema: entities, identifiers, sources, data_points, audit_log_entries

Revision ID: 2a27476037ab
Revises: 
Create Date: 2026-09-07 13:13:27.368786

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2a27476037ab'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('source_key', sa.String(length=50), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_timestamp', 'audit_log_entries', ['timestamp_utc'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('primary_exchange', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('license_note', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('data_points',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('retrieved_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=False),
    sa.Column('value_normalized', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('value_kind', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_data_points_entity_metric_period', 'data_points', ['entity_id', 'metric_name', 'period_end'], unique=False)
    op.create_index('ix_data_points_point_in_time', 'data_points', ['entity_id', 'metric_name', 'retrieved_at_utc'], unique=False)
    op.create_table('entity_identifiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('id_type', sa.String(length=20), nullable=False),
    sa.Column('id_value', sa.String(length=100), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_type', 'id_value', 'exchange', 'valid_from', name='uq_identifier_scope')
    )
    op.create_index('ix_entity_identifiers_lookup', 'entity_identifiers', ['id_type', 'id_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_identifiers_lookup', table_name='entity_identifiers')
    op.drop_table('entity_identifiers')
    op.drop_index('ix_data_points_point_in_time', table_name='data_points')
    op.drop_index('ix_data_points_entity_metric_period', table_name='data_points')
    op.drop_table('data_points')
    op.drop_table('sources')
    op.drop_table('entities')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
