"""Add news_items table

Revision ID: b535434376cf
Revises: c4aac46133db
Create Date: 2026-09-07 15:19:02.095081

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b535434376cf'
down_revision: str | Sequence[str] | None = 'c4aac46133db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('source_category', sa.String(length=30), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'content_hash', name='uq_news_items_source_hash')
    )
    op.create_index('ix_news_items_entity_published', 'news_items', ['entity_id', 'published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_items_entity_published', table_name='news_items')
    op.drop_table('news_items')
    # ### end Alembic commands ###
