"""Add SIC classification to entities

Revision ID: c4aac46133db
Revises: 2a27476037ab
Create Date: 2026-09-07 14:17:46.840310

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c4aac46133db'
down_revision: str | Sequence[str] | None = '2a27476037ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('sic_code', sa.String(length=10), nullable=True))
    op.add_column('entities', sa.Column('sic_description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entities', 'sic_description')
    op.drop_column('entities', 'sic_code')
    # ### end Alembic commands ###
